name = "ai-prompt-library"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://prompt-library.coscient.workers.dev"

[build]
command = ""

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://prompt-library.coscient.workers.dev"

[env.staging.vars]
ENVIRONMENT = "staging"
API_BASE_URL = "https://prompt-library.coscient.workers.dev"
